#!/usr/bin/env bash
#
sudo apt install software-properties-common git
sudo apt-add-repository --yes --update ppa:ansible/ansible
sudo apt install ansible
git clone https://github.com/adelplace/ansible.git
cd ansible
./run-playbook
