- name: Install apps with ubuntu
  become: true
  apt:
    name:
      [
        "fonts-firacode",
        "curl",
        "tmux",
        "fzf",
        "bat",
        "flatpak",
        "direnv",
        "stow",
        "build-essential",
        "ripgrep",
        "gimp",
        "fd-find",
      ]
    state: present
  tags:
    - ubuntu

- name: Remove neovim default install
  become: true
  ansible.builtin.apt:
    name: [neovim, fzf]
    state: absent
  tags:
    - ubuntu

- name: Install apps with pacman
  become: true
  pacman:
    name:
      [
        "ttf-fira-code",
        "curl",
        "tmux",
        "fzf",
        "bat",
        "direnv",
        "stow",
        "ripgrep",
        "gimp",
        "fd",
        "nvim",
      ]
    state: present
  tags:
    - arch
