- name: Install apps
  become: true
  apt:
    name:
      [
        "fonts-firacode",
        "curl",
        "tmux",
        "fzf",
        "bat",
        "flatpak",
        "direnv",
        "stow",
        "build-essential",
        "ripgrep",
        "gimp",
        "fd-find",
      ]
  tags:
    - install
    - neovim
    - core
