- name: Add Docker GPG apt Key
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add repository into sources list
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present
    filename: docker

- name: Install docker-ce
  become: true
  apt:
    name:
      [
        "docker-ce",
        "docker-ce-cli",
        "containerd.io",
        "docker-buildx-plugin",
        "docker-compose-plugin",
      ]
    state: latest
    update_cache: true

- name: Add user to docker group
  become: true
  user:
    name: adelplace
    groups: docker
    append: yes
