- name: Installing stow
  apt: name=stow
  tags:
    - install
    - dotfiles
    - stow

- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: "git@github.com:adelplace/dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: no
    accept_hostkey: yes
    version: master
  tags:
    - install
    - dotfiles
    - stow

- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./stow.sh
  tags:
    - install
    - dotfiles
    - stow
