- name: Installing stow with ubuntu
  become: true
  apt:
    name: stow
    state: present
  tags:
    - ubuntu

- name: Installing stow with pacman
  become: true
  pacman:
    name: stow
    state: present
  tags:
    - arch

- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: "git@github.com:adelplace/dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: true
    update: false
    accept_hostkey: true
    version: master

- name: Stow dotfiles
  ansible.builtin.shell: cd $HOME/.dotfiles && ./stow.sh
