- name: Cloning fzf
  ansible.builtin.git:
    repo: "https://github.com/junegunn/fzf.git"
    dest: "{{ lookup('env', 'HOME') }}/.fzf"
    recursive: false
    update: false
    accept_hostkey: true
    version: master
  tags:
    - ubuntu

- name: Install fzf
  ansible.builtin.shell: ~/.fzf/install
  tags:
    - ubuntu

- name: Install fzf with pacman
  become: true
  pacman:
    name: fzf
    state: present
  tags:
    - arch
